#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------------
 *     process
 *     ----------------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2025
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

function
  _global_get() {
  let
    _global;
  if ( typeof window === 'undefined' &&
       ( typeof global !== 'undefined' && global.global === global ) &&
       typeof __webpack_require__ !== 'function' ) {
    _global =
      global;
  }
  if ( typeof(
         window) != "undefined" ) {
    _global =
      window;
  }
  return _global;
}

function
  _fs_module_get() {
  let
    _module_found,
    _module_name;
  const
    _fs_module_names = [
      "_fs",
      "_fs_module",
      "fs",
      "fs_module"
    ];
  const
    _global =
      _global_get();
  _module_found =
    false;
  for ( _module_name of _fs_module_names ) {
    if ( _module_name in _global ) {
      _fs_module =
        _global[
          _module_name];
      _module_found =
        true;
      break;
    }
  }
  if ( ! _module_found ) {
    _fs_module =
      require(
        "tmcfs");
  }
  return _fs_module;
}

function
  _browser_process_module_get(
    _fs_module) {
  if ( typeof(
         _fs_module) == "undefined" ||
       _fs_module == "" ) {
    _fs_module =
      _fs_module_get();
  }
  const
    _process =
      {};
  _process[
    "chdir"] =
      _chdir;
  _process[
    "cwd"] =
      _cwd;
  _process[
    "exit"] =
      _exit;
  return _process;
}

function
  _process_module_auto_detect(
    _fs_module) {
  let
    _process;
  if ( _fs_module == "" ||
       typeof(
         _fs_module) === 'undefined' ) {
    _fs_module =
      _fs_module_get();
  }
  if ( typeof window === 'undefined' &&
       ( typeof global !== 'undefined' && global.global === global ) &&
       typeof __webpack_require__ !== 'function' ) {
    _process =
      require(
        "node:process");
    _process[
      "browser"] =
      false;
  }
  else {
    _process =
      _browser_process_module_get(
        _fs_module);
  }
  return _process;
}

function
  _process_module_get(
    _module_name) {
  //   _fs_module) {
  let
    _process;
  _fs_module =
    _fs_module_get();
  if ( _module_name == "" ||
       typeof(
         _module_name) === 'undefined' ) {
    _process =
      _process_module_auto_detect(
        _fs_module);
  }
  else if ( _module_name == 'process-browserify' ) {
    _process =
      _browser_process_module_get(
        _fs_module);
  }
  else if ( _module_name == 'node:process' ) {
    _process =
      require(
        _module_name);
    _process[
      "browser"] =
      false;
  }
  else if ( _module_name == 'process' ) {
    _process =
      _process_module_auto_detect(
        _fs_module);
  }
  else {
    const
      _msg =
        "Unknown process module " +
        `'${_module_name}'.`.
    const
      _error =
      { "msg":
          _msg };
    console.error(
      _msg);
    throw _error
  }
  return _process;
}

function
  _cwd(
    _fs_module) {
  if ( typeof(
         _fs_module) == "undefined" ||
       _fs_module == "" ) {
    _fs_module =
      _fs_module_get();
  }
  return _fs_module.CURRENT_DIR;
}

function
  _chdir(
    _dir,
    _fs_module) {
  let
    _return;
  if ( typeof(
         _fs_module) == "undefined" ||
       _fs_module == "" ) {
    _fs_module =
      _fs_module_get();
  }
  const
    _dir_exists =
      _fs_module.isDir;
  if ( _dir_exists(
         _dir) ) {
    _fs_module.CURRENT_DIR =
      _dir;
    _return =
      true;
  }
  else {
    _return =
      false;
    const
      _msg =
        `Directory '${_dir}' ` +
        "does not exist.";
    _msg_error(
      _msg,
      0);
  }
  return _return;
}

function
  _exit(
    _code) {
  return _code;
};

_fs_module =
  _fs_module_get();

const
  _process =
    _process_module_auto_detect(
      _fs_module);

module.exports =
  _process;
module.exports.getModule =
  _process_module_get;
