#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------------
 *     process
 *     ----------------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2025
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/* Browser mocks */

function
  _exit(
    _code) {
  return _code;
};

const
  _echo2 =
    console.error;

function
  _global_get() {
  let
    _global;
  if ( typeof window === 'undefined' &&
       ( typeof global !== 'undefined' && global.global === global ) &&
       typeof __webpack_require__ !== 'function' ) {
    _global =
      global;
  }
  if ( typeof(
         window) != "undefined" ) {
    _global =
      window;
  }
  return _global;
}

function
  _env_get(
    _variable) {
  let
    _value;
  const
    _variable_type =
      typeof(
        _variable);
  const
    _global =
      _global_get();
  if ( _variable_type != "undefined" ) {
    _value =
      _global[
        _variable];
    return _value;
  }
  return global;
};


async function
  _fs_module_get() {
  let
    _fs_module,
    _module_found,
    _module_name;
  const
    _fs_module_names = [
      "_fs",
      "_fs_module",
      "fs",
      "fs_module"
    ];
  const
    _global =
      _global_get();
  _module_found =
    false;
  for ( _module_name of _fs_module_names ) {
    if ( _module_name in _global ) {
      _fs_module =
        _global[
          _module_name];
      _module_found =
        true;
      break;
    }
  }
  if ( ! _module_found ) {
    _fs_module =
      await import(
        "tmcfs");
  }
  return _fs_module;
}

async function
  _stream_module_get() {
  let
    _module_found,
    _module_name,
    _stream_module;
  const
    _stream_module_names = [
      "_stream",
      "_stream_module",
      "stream",
      "stream_module"
    ];
  const
    _global =
      _global_get();
  _module_found =
    false;
  for ( _module_name of _stream_module_names ) {
    if ( _module_name in _global ) {
      _stream_module =
        _global[
          _module_name];
      _module_found =
        true;
      break;
    }
  }
  if ( ! _module_found ) {
    _stream_module =
      await import(
        "stream-browserify");
  }
  return _stream_module;
}

async function
  _browser_process_module_get(
    _fs_module,
    _stream_module) {
  if ( typeof(
         _fs_module) == "undefined" ||
       _fs_module == "" ) {
    _fs_module =
      await _fs_module_get();
  }
  if ( typeof(
         _stream_module) == "undefined" ||
       _stream_module == "" ) {
    _stream_module =
      await _stream_module_get();
  }
  const
    _stdout =
      await _stdout_get(
        _stream_module);
  const
    _process =
      {};
  _process[
    "argv"] =
      _argv;
  _process[
    "chdir"] =
      _chdir;
  _process[
    "cwd"] =
      _cwd;
  _process[
    "env"] =
      _env_get();
  _process[
    "envGet"] =
      _env_get;
  _process[
    "exit"] =
      _exit;
  _process[
    "stdout"] =
      _stdout;
  return _process;
}

async function
  _process_module_auto_detect(
    _fs_module,
    _stream_module) {
  let
    _process;
  const
    _fs_module_type =
      typeof(
        _fs_module);
  const
    _stream_module_type =
      typeof(
        _stream_module);
  if ( _fs_module_type === 'undefined' ||
         _fs_module === "" ) {
    _fs_module =
      await _fs_module_get();
  }
  if ( _stream_module_type === 'undefined' ||
       _stream_module === "" ) {
    _stream_module =
      await _stream_module_get();
  }
  if ( typeof window === 'undefined' &&
       ( typeof global !== 'undefined' && global.global === global ) &&
       typeof __webpack_require__ !== 'function' ) {
    const
      _process_module =
        await import(
          "node:process");
    _process =
      _process_module.default;
    _process[
      "browser"] =
      false;
    _process[
      "envGet"] =
      _env_get;
  }
  else {
    _process =
      await _browser_process_module_get(
        _fs_module,
        _stream_module);
  }
  return _process;
}

async function
  _process_module_get(
    _module_name) {
  //   _fs_module) {
  let
    _process;
  const
    _fs_module =
      await _fs_module_get();
  const
    _stream_module =
      await _stream_module_get();
  if ( _module_name == "" ||
       typeof(
         _module_name) === 'undefined' ) {
    _process =
      await _process_module_auto_detect(
        _fs_module,
        _stream_module);
  }
  else if ( _module_name == 'process-browserify' ) {
    _process =
      await _browser_process_module_get(
        _fs_module,
        _stream_module);
  }
  else if ( _module_name == 'node:process' ) {
    const
      _process_module =
        await import(
          _module_name);
    _process =
      _process_module.default;
    _process[
      "browser"] =
      false;
    _process[
      "envGet"] =
      _env_get;
  }
  else if ( _module_name == 'process' ) {
    _process =
      await _process_module_auto_detect(
        _fs_module,
        _stream_module);
  }
  else {
    const
      _msg =
        "Unknown process module " +
        `'${_module_name}'.`.
    const
      _error =
      { "msg":
          _msg };
    _echo2(
      _msg);
    throw _error
  }
  return _process;
}

function
  _argv(
    _key_name) {
  let
    _assignment,
    _assignments,
    _key,
    _key_value,
    _location,
    _msg,
    _result,
    _url,
    _value;
  if ( typeof(
         _key_name) === 'undefined' ||
       _key_name == "" ||
       _key_name == null ) {
    _key_name =
      "";
  }
  const
    _return =
      [];
  _location =
    window.location;
  _url =
    _location.search.substring(
      1);
  _assignments =
    _url.split(
      '&');
  for ( _result =
          0;
        _result <
          _assignments.length;
        _result++ ) {
    _assignment =
      _assignments[
        _result];
    _key_value =
      _assignment.split(
        '=');
    _key =
      _key_value[
        0];
    if ( _key.length < 2 ) {
      _return.push(
        `-${_key}`);
    }
    else {
      _return.push(
        `--${_key}`);
    }
    if ( _key == _key_name ||
         _key_name == "" ) {
      _value =
        _key_value[
          1];
      _return.push(
        _value);
    }
  }
  return _return;
}

async function
  _cwd(
    _fs_module) {
  if ( typeof(
         _fs_module) == "undefined" ||
       _fs_module === "" ) {
    _fs_module =
      await _fs_module_get();
  }
  return _fs_module.CURRENT_DIR;
}

async function
  _chdir(
    _dir,
    _fs_module) {
  let
    _return;
  if ( typeof(
         _fs_module) == "undefined" ||
       _fs_module === "" ) {
    _fs_module =
      await _fs_module_get();
  }
  const
    _dir_exists =
      _fs_module.isDir;
  if ( _dir_exists(
         _dir) ) {
    _fs_module.CURRENT_DIR =
      _dir;
    _return =
      true;
  }
  else {
    _return =
      false;
    const
      _msg =
        `Directory '${_dir}' ` +
        "does not exist.";
    const
      _exception = {
        "msg":
          _msg
      };
    _echo2(
      _msg);
    throw _exception;
  }
  return _return;
}

async function
  _stdout_get(
    _stream_module) {
  let
    _stdout;
  _stdout =
    _stream_module;
  if ( typeof(
         _stream_module) == "undefined" ||
       _stream_module == "" ||
       _stream_module == {} ) {
    _stdout =
      await _stream_module_get();
  }
  return _stdout;
}


const
  _fs_module =
    await _fs_module_get();
const
  _stream_module =
    await _stream_module_get();

const
  _process =
    await _process_module_auto_detect(
      _fs_module,
      _stream_module);

// ES6 module exports

const
  getModule =
    _process_module_get;
export default _process;
export {
  getModule
};

// Common Javascript exports

// module.exports =
//   _process;
// module.exports.getModule =
//   _process_module_get;
